// <auto-generated />
using System;
using CRUD.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUD.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUD.DAL.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = new Guid("450271d8-0091-4bf4-beb0-b899e026560e"),
                            Age = 67,
                            Name = "Andrzej"
                        },
                        new
                        {
                            Id = new Guid("db67e008-1c68-463e-a7b2-e75ad5a82a7f"),
                            Age = 44,
                            Name = "Henryk"
                        });
                });

            modelBuilder.Entity("CRUD.DAL.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PagesCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b11e85fc-2d5a-48fa-ba59-3d5c396bc68e"),
                            AuthorId = new Guid("450271d8-0091-4bf4-beb0-b899e026560e"),
                            CategoryId = new Guid("db67e008-1c68-463e-a7b2-e75ad5a82a7a"),
                            PagesCount = 320,
                            Title = "Wiedźmin"
                        },
                        new
                        {
                            Id = new Guid("981a1ff3-5390-497f-8db5-f6a30c441b89"),
                            AuthorId = new Guid("db67e008-1c68-463e-a7b2-e75ad5a82a7f"),
                            CategoryId = new Guid("db67e008-1c68-463e-a7b2-e75ad5a82a7a"),
                            PagesCount = 280,
                            Title = "Krzyżacy"
                        });
                });

            modelBuilder.Entity("CRUD.DAL.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db67e008-1c68-463e-a7b2-e75ad5a82a7a"),
                            Description = "Książki o tematyce fantasy",
                            IsActive = true,
                            Name = "Fantasy"
                        });
                });

            modelBuilder.Entity("CRUD.DAL.Entities.Book", b =>
                {
                    b.HasOne("CRUD.DAL.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUD.DAL.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
