// <auto-generated />
using System;
using CRUD.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUD.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200917202543_Author")]
    partial class Author
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUD.DAL.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a49272f0-b645-4e5c-80a7-343de5babcfd"),
                            Age = 67,
                            Name = "Andrzej"
                        },
                        new
                        {
                            Id = new Guid("08edc18a-4151-425f-af2c-fcbda9463f0d"),
                            Age = 44,
                            Name = "Mareczek"
                        });
                });

            modelBuilder.Entity("CRUD.DAL.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PagesCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d5a68c2-5312-4ced-a657-46c43ae8c5a9"),
                            PagesCount = 320,
                            Title = "Wiedźmin"
                        },
                        new
                        {
                            Id = new Guid("b266db67-8a1f-4276-86c9-e78254885795"),
                            PagesCount = 280,
                            Title = "Krzyżacy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
